### ISSUE TITLE
WebGPU logo/mark?

### ISSUE THREAD

**Issue by koalie** [gpuweb/admin#14]
Hello!

As far as I could find, there isn't a logo or mark for WebGPU.
We've gotten a request for one from someone who most likely wants to mention WebGPU in a talk.
Logos or Marks are useful for other things.

Has the group thought about creating one?
If you take free advice (\<insert grinning emoji\>), please consider using the W3C Blue! (#005A9C)

**Comment by grorg** [comment]
Hi @koalie 

We haven't got a logo. We discussed it briefly, because someone made one for us but it was too similar to the WebGL logos.

We'll consider all suggestions, as long as they are willing to hear negative feedback 😝 

In the meantime, I suggest they use "WebG💩"

**Comment by cerisano** [comment]
The [WGPU project](https://github.com/gfx-rs/wgpu) (implementation of the [WebGPU native API](https://github.com/webgpu-native/webgpu-headers)) already has a logo, and even a rather fetching tee.

![image](https://user-images.githubusercontent.com/68128706/97454693-6a159280-190d-11eb-89f4-45a20a44646c.png)

**Comment by toji** [comment]
Resurrecting and old thread because I saw someone use the WGPU logo in a slide deck yet again during a WebGL meetup today and it made me sad. Not because I have anything against the WGPU logo, which is awesome, but because unless that team wants to donate it to the WebGPU working group we should probably stop accidentally appropriating it.

Anyway, I've had a back-of-the-napkin sketch floating around on my desk for a bit and decided to mock it up in Photoshop real quick and throw it out as a proposal:

![WebGPU-Logo-Concept](https://user-images.githubusercontent.com/805273/111537616-e5df7280-8728-11eb-98aa-59786481d8a0.png)

The basics are that I strongly wanted something with triangles at its core, since that's the basis of so much of what these APIs do, and also really liked the idea of highlighting the "Web" part, in this case by forming an abstract "W". I also like that this hints at fractal complexity while still staying simple and easy to read, which I feel aligns with the API goals well. 😁

I'm not good with colors or fonts, so consider those placeholders. For the colors I started with the aformentioned W3C Blue for the biggest triangle and just kinda nudged the color picker up for each subsequent triangle. 😅 You could also have the same effect with any other base color or have it be a mix of colors like the bottom right variant suggests.

**Comment by jdarpinian** [comment]
Neat! I think I like the one with space between the triangles. Although replacing the W in WebGPU probably works better without space between the triangles.

**Comment by litherum** [comment]
A few design thoughts from Myles (not from Apple):

1. We should choose a font that isn't one of the default installed fonts on common OSes - this is generally considered a design sin. Bonus points if we can use the same font that the W3C uses in its communications.
2. I don't see any reason to bold "GPU". I've never seen anyone bold the "GPU" before when discussing this topic, and doing so here seems strange and unfamiliar.
3. I think the fake shadows won't age well. (The light source seems to be in a different place for each of the shadows...)
4. I like the visual pun of using triangles.

**Comment by toji** [comment]
Thanks for the feedback!

 1. Yeah, I'm not very opinionated about the font (and I am under no circumstances to be trusted with colors). I'd want someone with more design experience to make some better informed selections in those areas.
 2. Not attached to making "GPU" bold. I had no particular reason behind it.
 3. Yeah, the fake shadows are extremely haphazard! If we liked the concept (kinda gives it an origami look) I'd definitely want to put more thought into the placement and direction of the shadows, an possibly even try to physically light it. For what it's worth I think the flat color variants are nicer, though.
 4. 🔺❤️

**Comment by koalie** [comment]
Hi Myles, all,

> On 22 Mar 2021, at 23:47 , Myles C. Maxfield ***@***.***> wrote:
> 
> 	• We should choose a font that isn't one of the default installed fonts on common OSes - this is generally considered a design sin. Bonus points if we can use the same font that the W3C uses in its communications.

FYI: The font in the W3C logo is Base Twelve Sans from Emigre Graphics.

Coralie


--
Coralie Mercier  -  W3C Marketing & Communications -  https://www.w3.org
***@***.*** +337 810 795 22 https://www.w3.org/People/Coralie/

**Comment by toji** [comment]
Thanks Coralie!

Taking into account some of the feedback above, here's what my proposal would look like with the Base Twelve Sans font and removing the bold from "GPU":

![WebGPU-Logo-Concept-sheet-base-twelve-sans](https://user-images.githubusercontent.com/805273/112176904-b8297c00-8bb5-11eb-900f-cbc63b78b5e5.png)

I also noticed that the very distinctive "W" of this particular font already looks like overlapping triangles anyway, but the layout was flipped horizontally, so I gave that a try as well:

![WebGPU-Logo-Concept-sheet-base-twelve-sans-flipped](https://user-images.githubusercontent.com/805273/112178830-5538e480-8bb7-11eb-9cc6-6892c09e9785.png)

Personally I don't think it "reads" as well when flipped like this (at least as an English reader that tends to naturally look at things left-to-right") and I don't know if anyone will pick up the correlation in the orientation between the W in the text and the W made by the triangles. 🤷‍♀️ Also, I got a comment internally that the triangles didn't necessarily have to be equilateral, so I tried a narrow version that matches the angles of the text's W:

![WebGPU-Logo-Concept-sheet-base-twelve-sans-narrow](https://user-images.githubusercontent.com/805273/112180121-80700380-8bb8-11eb-8687-2e70c95584ee.png)

I'm not particularly a fan of the this version, though I will admit that it works a bit better in the horizontal version.

**Comment by koalie** [comment]
It may be just me, but the kerning between "P" and "U" seems to need some manual adjustement: reducing the space a teeny bit.

**Comment by kainino0x** [comment]
> Personally I don't think it "reads" as well when flipped like this (at least as an English reader that tends to naturally look at things left-to-right") and I don't know if anyone will pick up the correlation in the orientation between the W in the text and the W made by the triangles.

Agreed.

> here's what my proposal would look like with the Base Twelve Sans font

FWIW, to my eye, this font is out of place here. Compared with the W3C logo, there's (1) more text and (2) more graphics (the W logo), and I think Base Twelve Sans is too opinionated/"interesting". The [WASM logo](https://github.com/carlosbaraza/web-assembly-logo) uses simpler font(s) but I can't figure out what font it is without opening the `.ai` file.

**Comment by jdarpinian** [comment]
How about something like Helvetica Neue Light? I also tried adding a different kind of gradient to the triangles with Unsharp Mask. Maybe not subtle enough.
<img src=https://user-images.githubusercontent.com/454184/116650388-d2cdde00-a935-11eb-8553-eb73eed2016b.png width=400>

**Comment by dneto0** [comment]
I just saw this all for the first time.

I really like the design concept. Great job @toji !
I'm +1 on the no-gaps version, the gaps version, and the several colours version.

(I personally like the endless ability to mutate Google-ish brands such as the Google logo and the Android "android" and still have them be very recognizable.  I know it's not for everyone.)

Personally, the fonts shown here look wrong to me.   Either ugly, "dated", or in the case of Helvetica Neue Light, too light.
I expect a font that lightweight font would not look good when shrunk down, e.g think of the mark/logo at the bottom right corner of a slide deck.  

Having read the TeXBook and Metafont book, and having absorbed some aesthetic preferences from them, I expect different font stylings would be needed for ideal rendering for different sizes.

**Comment by toji** [comment]
After the discussion on today's call, I went back to the logo and tried a few different fonts with it. I liked [Poppins](https://fonts.google.com/specimen/Poppins?preview.text=WebGPU&preview.text_type=custom) as a nice geometric, sans-serif font that works well at varying weights, though I'm certainly still up for suggestions! (Sorry, James. Didn't include your gradients to this one.)

![WebGPU-Logo](https://user-images.githubusercontent.com/805273/118553724-8cd68f80-b715-11eb-880e-0ef7f20bc4a2.png)

Also, simply because I could, I put together a [page that demonstrates the logo being rendered entirely with CSS](https://toji.github.io/webgpu-test/webgpu-css-logo.html)!
Is this useful? Almost certainly not! But it amuses me anyway. 😉

**Comment by javierluraschi** [comment]
Same SVG from @toji converted to PNG with transparency:

![webgpu-logo](https://user-images.githubusercontent.com/3478847/122788930-a6667c00-d26b-11eb-98de-6f0bd227e55d.png)

**Comment by edankwan** [comment]
I am not a designer but this is my take on it:
![image](https://user-images.githubusercontent.com/989103/123218560-c8f2d200-d4c3-11eb-8a67-9c7efe0ac541.png)

**Comment by Kangz** [comment]
Now that we agreed on this logo, can we add an svg to gpuweb/gpuweb so we can reference it everywhere?

**Comment by munrocket** [comment]
My take on it: 🕸️GPU

**Comment by munrocket** [comment]
<img src='https://svgshare.com/i/_Ky.svg' title='WebGPU Metallica' />

Another one: [colorful_metallica.svg](https://svgshare.com/s/_Ky)
