### ISSUE TITLE
Add some concurrency support to the goals?

### ISSUE THREAD

**Issue by Kangz** [gpuweb/admin#5]
One of the major improvements of explicit graphics APIs over older ones is that all of them support some sort of concurrency, at least in the recording of command lists / command buffers / encoders. Exposing the same sort of capabilities to the Web would be very beneficial too, so maybe we could add it to the top-level goals, or at least mention it as a stretch goal.

**Comment by othermaciej** [comment]
It seems like concurrency is more of an instrumental goal to enable better performance or nonblocking behavior, rather than an end in itself. For a charter, it might make more sense to list the things concurrency could enable as goals, and mention that concurrency is a likely way to help achieve them.

(I do agree concurrency support will almost certainly be needed though.)

**Comment by Kangz** [comment]
Sounds good as a mean to achieve a performance goal.
